# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Victorian N Scale Collective
email: vnsc1991@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Victorian N Scale Collective aims to promote and encourage the participation in and enjoyment of modelling of the railways of Victoria in N Scale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.vnsc.org.au/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
